"""Platform ad specifications, and checking copy against them.

Every platform has its own limits and its own idea of what a "character" is.
Getting this wrong means the ad is rejected on upload, or worse, accepted and
silently truncated mid-word in the middle of a live campaign.

This is deliberately deterministic and has nothing to do with the model. Copy
generated by an LLM is checked here before it is ever submitted, because
asking a model to count characters and trusting the answer is not a strategy.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from enum import Enum


class Platform(str, Enum):
    GOOGLE = "google"
    MICROSOFT = "microsoft"
    META = "meta"
    LINKEDIN = "linkedin"


class AssetType(str, Enum):
    HEADLINE = "headline"
    DESCRIPTION = "description"
    PRIMARY_TEXT = "primary_text"
    PATH = "path"


@dataclass(frozen=True)
class AssetSpec:
    max_length: int
    min_count: int
    max_count: int
    """Recommended length before the platform truncates in the feed. Not a
    rejection, just a warning - the copy still runs, it just gets cut."""
    recommended_length: int | None = None


# Sources: Google Ads RSA limits, Microsoft Advertising RSA (deliberately
# mirrors Google so campaigns import cleanly), Meta feed placements, LinkedIn
# single-image sponsored content.
SPECS: dict[Platform, dict[AssetType, AssetSpec]] = {
    Platform.GOOGLE: {
        AssetType.HEADLINE: AssetSpec(max_length=30, min_count=3, max_count=15),
        AssetType.DESCRIPTION: AssetSpec(max_length=90, min_count=2, max_count=4),
        AssetType.PATH: AssetSpec(max_length=15, min_count=0, max_count=2),
    },
    Platform.MICROSOFT: {
        AssetType.HEADLINE: AssetSpec(max_length=30, min_count=3, max_count=15),
        AssetType.DESCRIPTION: AssetSpec(max_length=90, min_count=2, max_count=4),
        AssetType.PATH: AssetSpec(max_length=15, min_count=0, max_count=2),
    },
    Platform.META: {
        AssetType.PRIMARY_TEXT: AssetSpec(
            max_length=500, min_count=1, max_count=5, recommended_length=125
        ),
        AssetType.HEADLINE: AssetSpec(
            max_length=255, min_count=1, max_count=5, recommended_length=40
        ),
        AssetType.DESCRIPTION: AssetSpec(
            max_length=255, min_count=0, max_count=5, recommended_length=30
        ),
    },
    Platform.LINKEDIN: {
        AssetType.PRIMARY_TEXT: AssetSpec(
            max_length=600, min_count=1, max_count=1, recommended_length=150
        ),
        AssetType.HEADLINE: AssetSpec(
            max_length=200, min_count=1, max_count=1, recommended_length=70
        ),
    },
}


def counted_length(text: str, platform: Platform) -> int:
    """How long the platform thinks this string is.

    Google and Microsoft count a full-width character - CJK, and the
    full-width Latin forms - as two. A headline of fifteen Japanese
    characters is at the thirty character limit exactly, and counting
    `len(text)` says fifteen and passes copy that gets rejected on upload.

    Meta and LinkedIn count code points, so `len` is right for those.
    """
    if platform in (Platform.GOOGLE, Platform.MICROSOFT):
        return sum(2 if unicodedata.east_asian_width(ch) in ("W", "F") else 1 for ch in text)
    return len(text)


# Google rejects emoji in search text ads outright. Meta and LinkedIn allow
# them. This covers the pictographic ranges, not every symbol in Unicode.
EMOJI = re.compile(
    "["
    "\U0001F300-\U0001F5FF"
    "\U0001F600-\U0001F64F"
    "\U0001F680-\U0001F6FF"
    "\U0001F900-\U0001F9FF"
    "\U00002600-\U000026FF"
    "\U00002700-\U000027BF"
    "]"
)

REPEATED_PUNCT = re.compile(r"([!?])\1+")
ALL_CAPS_WORD = re.compile(r"\b[A-Z]{4,}\b")

# Words that are fine in all caps because that is how they are written.
CAPS_ALLOWED = {
    "FAQ", "HTTP", "HTTPS", "SaaS", "API", "SDK", "CRM", "ERP", "SEO", "ROI",
    "B2B", "B2C", "SMS", "GDPR", "HIPAA", "PDF", "USA", "UK", "EU", "CA",
    "AWS", "GCP", "IOS", "CPU", "GPU", "SIM", "LTE",
}


@dataclass(frozen=True)
class Issue:
    asset_type: AssetType
    index: int
    code: str
    message: str
    fatal: bool
    """Fatal issues get the ad rejected. Non-fatal ones are quality problems -
    truncation, mostly - that still cost money but do not block the upload."""


def check_text(
    text: str, platform: Platform, asset_type: AssetType, index: int = 0
) -> list[Issue]:
    """Check one piece of copy."""
    spec = SPECS.get(platform, {}).get(asset_type)
    issues: list[Issue] = []

    if spec is None:
        return [
            Issue(asset_type, index, "UNSUPPORTED_ASSET",
                  f"{platform.value} has no {asset_type.value} asset", True)
        ]

    stripped = text.strip()

    if not stripped:
        return [Issue(asset_type, index, "EMPTY", "Asset is empty", True)]

    if stripped != text:
        issues.append(Issue(
            asset_type, index, "WHITESPACE",
            "Leading or trailing whitespace, which counts towards the limit", False))

    length = counted_length(text, platform)

    if length > spec.max_length:
        issues.append(Issue(
            asset_type, index, "TOO_LONG",
            f"{length} characters, limit is {spec.max_length}", True))
    elif spec.recommended_length and length > spec.recommended_length:
        issues.append(Issue(
            asset_type, index, "TRUNCATION_RISK",
            f"{length} characters; {platform.value} truncates around "
            f"{spec.recommended_length} in the feed", False))

    if platform in (Platform.GOOGLE, Platform.MICROSOFT):
        if EMOJI.search(text):
            issues.append(Issue(
                asset_type, index, "EMOJI",
                "Emoji are not allowed in search text ads", True))

        if REPEATED_PUNCT.search(text):
            issues.append(Issue(
                asset_type, index, "REPEATED_PUNCTUATION",
                "Repeated exclamation or question marks are rejected", True))

        for word in ALL_CAPS_WORD.findall(text):
            if word not in CAPS_ALLOWED:
                issues.append(Issue(
                    asset_type, index, "ALL_CAPS",
                    f"'{word}' is in full capitals, which is treated as "
                    f"excessive capitalisation", True))
                break

    return issues


def check_group(
    assets: dict[AssetType, list[str]], platform: Platform
) -> list[Issue]:
    """Check a whole ad: every asset, plus how many of each there are."""
    issues: list[Issue] = []
    platform_specs = SPECS.get(platform, {})

    for asset_type, spec in platform_specs.items():
        values = assets.get(asset_type, [])

        if len(values) < spec.min_count:
            issues.append(Issue(
                asset_type, -1, "TOO_FEW",
                f"{len(values)} {asset_type.value} assets, minimum is {spec.min_count}",
                True))

        if len(values) > spec.max_count:
            issues.append(Issue(
                asset_type, -1, "TOO_MANY",
                f"{len(values)} {asset_type.value} assets, maximum is {spec.max_count}",
                True))

    for asset_type, values in assets.items():
        for index, value in enumerate(values):
            issues.extend(check_text(value, platform, asset_type, index))

    # Duplicate headlines are accepted by the platform and waste an asset
    # slot, since the system will never show two identical headlines together.
    headlines = [h.strip().lower() for h in assets.get(AssetType.HEADLINE, [])]
    duplicates = {h for h in headlines if headlines.count(h) > 1}
    for duplicate in sorted(duplicates):
        issues.append(Issue(
            AssetType.HEADLINE, headlines.index(duplicate), "DUPLICATE",
            f"Headline {duplicate!r} appears more than once", False))

    return issues


def is_publishable(issues: list[Issue]) -> bool:
    """True when nothing would get the ad rejected."""
    return not any(issue.fatal for issue in issues)
